name: OceaniaChirstmasPet
version: '${project.version}'
main: net.oceaniacraft.oceaniachirstmaspet.OceaniaChirstmasPet
api-version: '1.20'
commands:
  2023christmaspet:
permissions:
  oceaniachristmaspet.admin:
